{% set name = "kubeflow-training" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kubeflow-training-{{ version }}.tar.gz
  sha256: 3c1b92dde4a0f2c86a677bf7b4b75bd44439e9ccec893e77e9cdd6aebf586958

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - certifi >=14.05.14
    - six >=1.10
    - setuptools >=21.0.0
    - urllib3 >=1.15.1
    - python-kubernetes >=23.6.0
    - retrying >=1.3.3

test:
  imports:
    - kubeflow.training
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kubeflow/training-operator/sdk/python
  summary: Training Operator Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyvelich
    - droctothorpe
    - iamthebot
    - tenzen-y
    - terrytangyuan
