{% set name = "kubeflow-training" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kubeflow-training-{{ version }}.tar.gz
  sha256: b4002ec3ad335f058b4e5393f193e69a7e195142e4926960fb7f868d22afd316

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - certifi >=14.05.14
    - six >=1.10
    - setuptools >=21.0.0
    - urllib3 >=1.15.1
    - python-kubernetes >=23.6.0
    - retrying >=1.3.3

test:
  imports:
    - kubeflow.training
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kubeflow/training-operator/sdk/python
  summary: Training Operator Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyvelich
    - droctothorpe
    - iamthebot
    - tenzen-y
    - terrytangyuan
