{% set name = "kubeflow-training" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kubeflow-training-{{ version }}.tar.gz
  sha256: b8b2fead3f0491793dbe24e6b0d7c73d4bce47bfd0c3dc362d38f620f69ec744

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=14.05.14
    - six >=1.10
    - setuptools >=21.0.0
    - urllib3 >=1.15.1
    - python-kubernetes >=23.6.0
    - retrying >=1.3.3

test:
  imports:
    - kubeflow.training
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kubeflow/training-operator/sdk/python
  summary: Training Operator Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyvelich
    - droctothorpe
    - iamthebot
    - tenzen-y
    - terrytangyuan
